### PR TITLE
create low-level methods for building and signing messages

### PR DESCRIPTION
**Pull request by willwhitney**
I'm migrating Hydrogen over to using `jmp`, and since the communication paradigm isn't receive-reply, I need new methods for building and signing Messages from scratch.

Once those methods were in place, I ported `Message.respond` to use them. It now creates a new response Message and fills it with the right content.

For clarity and encapsulation, I think `Message.respond` should probably be removed; code that uses this library can use `Message.buildResponse` to get the signed message themselves, then send it over the socket. But that's not in this PR.

### CODE REVIEW

**Comment by n-riesco** [comment]
Using the interface proposed in this PR, a message would be created from scratch like this:

``` js
var msg = new Message();

msg.fill({
    idents: idents,
    header: header,
    parentHeader: parentHeader,
    metadata: metadata,
    content: content,
});

socket.send(msg.sign());
```

Note `Message.prototype.fill` is not really necessary, you can already do:

``` js
var msg = new Message();

msg.idents = idents;
msg.header = header;
msg.parentHeader = parentHeader;
msg.metadata = metadata;
msg.content = content;
```

Do you really need `Message.prototype.sign()`?
If what you need is to send a signed message: `socket.send(msg.sign())`, I would define `Message.prototype.send()` instead.

---

I'm not happy with the current Message constructor. Its current interface was driven by IJavascript needs:

``` js
var msg = new Message(requestArguments, scheme, key);
```

this interface is unnecessarily ugly when an encrypted message is created from scratch:

``` js
var msg = new Message(undefined, scheme, key);
```

I think `requestArguments` doesn't belong to the constructor. I would rather have:

``` js
var msg = new Message(scheme, key);
msg.parse(requestArguments);
```

---

What do you think? Would something like the following satisfy your needs?

``` js
var msg = new Message(scheme, key);

msg.idents = idents;
msg.header = header;
msg.parentHeader = parentHeader;
msg.metadata = metadata;
msg.content = content;

msg.send(socket);
```

**Comment by willwhitney** [comment]
I would prefer to pull sending out of Message; it seems counterintuitive to have a message send itself, when Sockets are normally what has a `send` or `write` method. This is a style decision though, and as long as there's still a `sign` (which `send` can use) then I'm happy either way.

My reasoning behind adding `fill` is also stylistic; by having a method for this, we are then able to [change the internals | rename fields | do additional checking] without changing the API. It's usually good practice, especially in a shared library.

One thing that would be really nice is to pull out parsing from Message entirely. That way the semantics are really clean. `jmp.parseMessage(scheme, key, requestArguments)` would return a `jmp.Message`.

I totally agree with changing the constructor. What might make sense is to make the constructor take in an object (like `fill` does) to populate itself. Then Messages wouldn't get modified in place so much.

For me the ideal interface would look like this:

``` javascript
var receivedMessage = jmp.parseMessage(scheme, key, requestArguments);
// receivedMessage is a new Message object

var outgoingMessage = new jmp.Message(scheme, key, {
                              idents: <>, 
                              header: <>, 
                              parentHeader: <>, 
                              metadata: <>, 
                              content: <>, 
                          });
var signedMessage = outgoingMessage.sign();
socket.send(signedMessage);
```

You could also have Socket automatically do signature-checking, parsing, and signing. Then the interaction would be:

``` javascript
var outgoingMessage = new jmp.Message({
                              idents: <>, 
                              header: <>, 
                              parentHeader: <>, 
                              metadata: <>, 
                              content: <>, 
                          });
socket.send(signedMessage);
```

or in the example from the docs,

``` javascript
shellSocket.on("message", function(request) {
    // `request` is an instance of `jmp.Message`
    // if its signature didn't check out, the socket throws an error
    //     and this code is never run

    // do something with the request
    var msg_type = request.header.msg_type;
    var content = request.content;

    var response = request.buildResponse(messageType, responseContent, protocolVersion);
    // response is a new Message object

    // respond
    shellSocket.send(response);
});
```

I think that would be super nice, because after the creation of the Socket you'd never have to worry about keys and signing schemes again — the communication channel itself is authenticated.

**Comment by n-riesco** [comment]
Let me sum up your points (please, correct me if I'm wrong)
1. On **`Message.send(socket)`**:  
   You argue that it may be found "counter-intuitive to have a message send itself".  
   
   I imagine this piece of criticism comes from following an OOP paradigm where `subject.verb(object)`. Please, see an alternative proposal at the end of this message.
2. On **`Message.fill(properties)`**:  
   You argue that _"it's usually good practice"_ "having a method for this, we are then able to [change the internals | rename fields | do additional checking] without changing the API".  
   Note that Javascript, like C#, lets us define properties as getters and setters so that any additional checking is already possible.  
   Also note that renaming the fields of the object passed to `Message.fill(properties)` is also a change of API.
3. On **`jmp.parseMessage(scheme, key, requestArguments)`**:  
   I won't go for the easy piece of criticism and argue that this change isn't very OOP.  
   The main concern I have about this change is that if `Message.parse` is taken out of the `Message` class, it will be more difficulty for `JMP` users to discover the parse functionality.
4. On **`Message.sign()`**:  
   I feel you haven't addressed the criticism I made about `Message.sign()` in my previous message: the proposed change makes the use of `JMP` more verbose. I don't see a use-case for making `sign` public.

---

**Alternative proposal**

With this proposal I'm trying:
- Minimise verbosity for users of `JMP`
- Avoid stutter. e.g. `msg.parseRequest(request)`
- Keep `jmp.Socket` as a thin wrapper of `zmq.Socket`, i.e. same API
- Address points 1-4 above

Here's the alternative proposal:
1. Class `Message`:
   - Constructor `function Message([scheme], [key], [frames])`  
     where `frames` is an object with the message frames, i.e.: idents, header, ...
   - Method `Message.set(frames)`  
     This is essentially equivalent to `msg.fill(frames)` in your PR. I prefer `set` because this method is setter-like. It sets the message properties.
   - Method `Message._format()`  
     This is essentially equivalent to `msg.sign()` in your PR. It returns an array suitable for sending by a `jmp.Socket`. I think `_format` is more appropriate than `sign` because the message can be unsigned. My feeling is that we shouldn't make this method public. I don't see a use-case for `JMP` users.
   - Method `Message.parse(request)`  
     I would like to keep this method for the reason stated above in point 3.
   - Properties  
     I would like to keep accessing the message frames using properties. This is very convenient for users.
2. Class `Socket`:  
   As I said above, I would like to keep `jmp.Socket`'s and `zmq.Socket`'s API the same. To do so, instead of defining `Socket.sendMessage(data)` I would override `Socket.send(message)` and if `data instanceof Message` then call `message._format()` before sending the message.

Using this proposal a message would be created and sent like this:

``` js
var msg = new Message(scheme, key,
    idents: idents,
    header: header,
    parentHeader: parentHeader,
    metadata: metadata,
    content: content,
});

socket.send(msg);
```

And a response to a request would be created and sent like this:

``` js
var msg = new Message(scheme, key);
msg.parse(requestArguments);
socket.send(msg);
```

---

@rgbkrk Kyle, since the changes we're discussing here will break your code, please, could you give us your thoughts?

**Comment by willwhitney** [comment]
This sounds pretty good. It's a little noisy for every message to have to manage its own signing scheme and key, but if you want to keep the `jmp.Socket` API the same as `zmq.Socket`'s that's fine.

I think this will be a big improvement for general-purpose use of `jmp`!

**Comment by rgbkrk** [comment]
Don't worry about me as a consumer, I can always shrink wrap if needed and would rather change the API if it makes sense (as long as SemVer is judiciously applied).

This does fit right with the abstractions I'd expect as a consumer. I'll know the scheme and key for a given socket, I don't want to have to know how to use them (be oblivious to the details of signing so we get it right for the downstream users).

Not that it should end up in this PR but I'd eventually see us in a position of providing a `Session` object. We three have all implemented it in separate ways within ijavascript, Hydrogen, and sidecar. During SciPy when I'm hacking with folks on some other electron prototypes, we'll certainly be doing the same again.

**Comment by n-riesco** [comment]
I've pushed version 0.1.0 to github, but I haven't published it yet on `npm` so that you have time to update your `package.json` files.

I took on board Will's suggestion and removed `scheme` and `key` from `jmp.Message`. I also simplified `jmp.Message` further and now it only has one public method: `respond`.

@willwhitney At the moment the Message constructor doesn't take any arguments. Please, let me know if you would like the constructor to take an object of properties as in some of the proposals above.

At the moment, to create an object from scratch and send it over a jmp.Socket:

``` js
var msg = new Message();

msg.idents = idents;
msg.header = header;
msg.parentHeader = parentHeader;
msg.metadata = metadata;
msg.content = content;

socket.send(msg);
```

To listen on a `jmp.Socket` and decode the message automatically:

``` js
serverSocket.on("message", function(msg) {
    msg.respond(
        socket, responseMessageType, responseContent, reponseMetadata
    );
});
```

I've updated `README.md` with a detailed example of use.

**Comment by willwhitney** [comment]
This looks great!

I do prefer to have the Message properties passed in the constructor than set directly, but if this is the way you want to do it I'll just write a `buildMessage` function in Hydrogen.

**Comment by n-riesco** [comment]
It's OK. I will update de constructor.

**Comment by willwhitney** [comment]
After those changes to the constructor, this seems ready to go. I've got a build of Hydrogen using this (from master) and it's a big improvement. Thanks for your help!

**Comment by rgbkrk** [comment]
What's your release strategy @n-riesco?

I don't see `0.1.0` on npm though that's the number on the current `package.json`. Have you tried `npm version` out? It's been pretty handy to cut a release as `npm version minor && git push --tags && npm publish` (or `npm version patch`, depending on level).

**Comment by n-riesco** [comment]
I wanted to give users a chance to update their packages before breaking compatibility.

I've just pushed to github a commit with constructor changes and published it at `npm` as v0.1.0.

**Pull request closed without merging**
