### PR TITLE
[Discuss] Rely on zmq-prebuilt

### PR DESCRIPTION
**Pull request by rgbkrk**
I'd like to start trying out the use of a prebuilt zmq with nteract and Hydrogen. It does make the Linux and Mac story easier for install. The Windows story is not complete, as far as I know.

I'm not expecting you to merge this, I'll probably create a jmp-prebuilt package that we can rely on in `enchannel-zmq-backend`.

### CODE REVIEW

**Comment by n-riesco** [comment]
I tried to play with this, but I can't without upgrading my Ubuntu 14.04 machines (something I'm not looking forward to, [just yet](https://bugs.launchpad.net/ubuntu/+source/init-system-helpers/+bug/1509816)).

**Comment by rgbkrk** [comment]
What makes this not work on your current machine? Will this impact other Ubuntu users?

**Comment by n-riesco** [comment]
On 21/03/16 23:22, Kyle Kelley wrote:

> What makes this not work on your current machine? Will this impact other Ubuntu users?

I've just tested the installation in two Ubuntu 14.04 machines.

The 64bit machine completes the installation with just a few warnings:

```
$ npm i zmq-prebuilt
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
-
> zmq-prebuilt@0.0.3 install /home/nriesco/node_modules/zmq-prebuilt
> prebuild --install

zmq-prebuilt@0.0.3 node_modules/zmq-prebuilt
├── bindings@1.2.1
├── nan@2.1.0
└── prebuild@2.9.2 (os-homedir@1.0.1, expand-template@1.0.2, noop-logger@0.1.1, xtend@4.0.1, github-from-package@0.0.0, tar-fs@1.11.1, minimist@1.2.0, async@1.5.2, mkdirp@0.5.1, rc@1.1.6, pump@1.0.1, simple-get@1.4.3, tar-stream@1.3.2, npmlog@2.0.3, ghreleases@1.0.4, node-gyp@3.3.1)
```

The 32bit machine cannot find prebuilt binaries and fails during compilation. I will post the log later on.

**Comment by n-riesco** [comment]
And here's the log for the 32 bit machine:

```
$ npm i zmq-prebuilt
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
\
> zmq-prebuilt@0.0.3 install /home/user/node_modules/zmq-prebuilt
> prebuild --install

prebuild WARN install Prebuilt binaries for node version v0.10.25 are not available
make: Entering directory `/home/user/node_modules/zmq-prebuilt/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
g++: error: ./Release/../../zmq/lib/libzmq.a: No such file or directory
make: *** [Release/obj.target/zmq.node] Error 1
make: Leaving directory `/home/user/node_modules/zmq-prebuilt/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/home/user/node_modules/zmq-prebuilt/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/home/user/node_modules/zmq-prebuilt/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at ChildProcess.EventEmitter.emit (events.js:98:17)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! zmq-prebuilt@0.0.3 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the zmq-prebuilt@0.0.3 install script.
npm ERR! This is most likely a problem with the zmq-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-83-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "zmq-prebuilt"
npm ERR! cwd /home/user
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/npm-debug.log
npm ERR! not ok code 0
```

**Comment by rgbkrk** [comment]
Ah! If you have a 32-bit machine, you can do the build for everyone and upload it.

**Comment by rgbkrk** [comment]
It looks like the 32-bit machine is missing the zmq headers (missing `libzmq.a`).

**Comment by n-riesco** [comment]
On 22/03/16 12:48, Kyle Kelley wrote:

> Ah! If you have a 32-bit machine, you can do the build for everyone and upload it.

What do I need to do?

**Comment by rgbkrk** [comment]
You'll need a GitHub token that has scopes for upload to nteract/zmq-prebuilt and `$GITHUB_TOKEN` set as an environment variable. Then there are two ways of doing the build+upload:

## Locally

```
npm install
npm install -g prebuild
prebuild --all -u $GITHUB_TOKEN
```

## In Docker (assuming local 32-bit Docker)

```
docker build -t zmqprebuilt .
docker run -it zmqprebuilt prebuild --all -u $GITHUB_TOKEN
```

The core tech behind the scenes here is [prebuild](https://github.com/mafintosh/prebuild).

I'm going to add a section in the README for maintainers, since it's [currently buried away in a comment](https://github.com/nteract/zmq-prebuilt/pull/8#issuecomment-189515795).

**Comment by n-riesco** [comment]
@rgbkrk I had `libzmq3-dev`, but even after removing `libzmq3-dev` and installing `libzmq-dev`, `npm i zmq-prebuilt` fails with the same message.

**Comment by n-riesco** [comment]
@rgbkrk There are several problems:
- [These lines](https://github.com/JustinTulloss/zeromq.node/blob/master/binding.gyp#L55-L72) are missing in `building.gyp`.
- `[[` [here](https://github.com/nteract/zmq-prebuilt/blob/6ecd64947b000103ab610686c49e49a805764508/build_libzmq.sh#L8) is a bashism.

**Comment by rgbkrk** [comment]
Gah! I forgot to include instructions for running the `build_zmq.sh` script that @minrk put together.

Min, any other pieces we need? Nico is putting this together for ijavascript and Hydrogen usage at the moment.

**Comment by lgeiger** [comment]
I tried `jmp-prebuilt` with hydrogen on Mac OS. Installation works fine but I get following error:
bildschirmfoto 2016-03-23 um 09 25 24
I can rebuild the package but that doesn't solve the error. Or am I missing something?

**Comment by n-riesco** [comment]
On 23/03/16 08:38, Lukas Geiger wrote:

> I tried |jmp-prebuilt| with hydrogen on Mac OS. Installation works fine but I get following error:
> bildschirmfoto 2016-03-23 um 09 25 24 https://cloud.githubusercontent.com/assets/13285808/13979724/afa7c2e2-f0da-11e5-9658-bb527e53d94c.png
> I can rebuild the package but that doesn't solve the error. Or am I missing something?

Oh! It looks like this isn't possible yet. See:

https://github.com/mafintosh/prebuild/issues/61

**Comment by lgeiger** [comment]
Oh! I see.

**Comment by rgbkrk** [comment]
Ok, that's weird. I've been using prebuilt modules with Electron right now quite happily. Guess it's not so good with Atom?

**Comment by rgbkrk** [comment]
We've got zmq prebuilt working much better now for OS X. @captainsafia is going to get Linux prebuilds working within the next week. Windows to follow.

I went ahead and bumped the version number on this PR.

**Comment by n-riesco** [comment]
@rgbkrk I'll test it tomorrow.

**Comment by n-riesco** [comment]
@rgbkrk The compilation scripts are still broken. See below

```
$ npm i ./src/github.com/jmp
|
> zmq-prebuilt@1.0.2 install /home/user/node_modules/jmp-prebuilt/node_modules/zmq-prebuilt
> prebuild --install

prebuild WARN install Prebuilt binaries for node version v4.4.7 are not available
make: Entering directory `/home/user/node_modules/jmp-prebuilt/node_modules/zmq-prebuilt/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
g++: error: ./Release/../../zmq/lib/libzmq.a: No such file or directory
make: *** [Release/obj.target/zmq.node] Error 1
make: Leaving directory `/home/user/node_modules/jmp-prebuilt/node_modules/zmq-prebuilt/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/home/user/node_modules/jmp-prebuilt/node_modules/zmq-prebuilt/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:87:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:172:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/home/user/node_modules/jmp-prebuilt/node_modules/zmq-prebuilt/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:87:13)
prebuild ERR! build     at ChildProcess.emit (events.js:172:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "./src/github.com/jmp"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! zmq-prebuilt@1.0.2 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the zmq-prebuilt@1.0.2 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the zmq-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls zmq-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/npm-debug.log

```

**Comment by n-riesco** [comment]
@rgbkrk 
Could you target the PR to the `jmp-prebuilt` branch?
I'm updating README.md to explain why.

**Comment by n-riesco** [comment]
@rgbkrk I've also noticed that this would be your first contribution to JMP! :smile: 

Please, could you update the AUTHORS file? I ask contributors to do so, to confirm their consent to distributing their contributions under the LICENSE terms.

**Comment by rgbkrk** [comment]
Ah, certainly. I can close this one and open a new one.

**Comment by rgbkrk** [comment]
> The compilation scripts are still broken.

We have an issue where you need to run our `build_libzmq.sh` script _before_ you run npm install. This only affects the developer, not the user since we have uploaded tarballs via `prebuild`. The Linux binaries haven't been uploaded yet though.

**Comment by n-riesco** [comment]
On 11/08/16 17:56, Kyle Kelley wrote:

> ```
> The compilation scripts are still broken.
> ```
> 
> This only affects the developer, not the user since we have uploaded tarballs via |prebuild|.

It affects users for which there are no tarballs.

Is it possible to revert to the original install script when binaries aren't available?

**Comment by rgbkrk** [comment]
> Is it possible to revert to the original install script when binaries aren't available?

Yeah, we're running into trouble with the `preinstall` options. Safia is working on that. I'll post when we're closer.

**Comment by rgbkrk** [comment]
Closing this PR for now, we can make a new one later.

**Pull request closed without merging**
