### PR TITLE
Use ZeroMQ 5.2.4 - fix build on Electron 9

### LINKED ISSUE #31: ZeroMq doesn't build for Electron 9
https://github.com/nteract/hydrogen/issues/2034

Edit:

I pushed a fix to ZeroMq itself. See this:
https://github.com/zeromq/zeromq.js/pull/444

### PR DESCRIPTION
**Pull request by aminya**
Fixes #31

### CODE REVIEW

**Comment by n-riesco** [comment]
"5" and "^5" are equivalent.

See https://semver.npmjs.com/ if you want to play with different combinations.

I don't find '^' and '~` readable.

**Comment by aminya** [comment]
@n-riesco I updated the PR to use the fixed ZeroMQ. I will release Hydrogen by a link to my GitHub branch for now until you merge this.

**Comment by n-riesco** [comment]
I see in https://www.npmjs.com/package/zeromq?activeTab=versions that zeromq@5.2.4 has already been released.
We don't need this PR, do we?

**Comment by aminya** [comment]
I updated ZeroMQ. This PR now includes the working ZeroMQ 5.

**Comment by n-riesco** [comment]
I'm sorry I wasn't clear before. This PR is not really necessary.
`"zeromq": "5"` describes exactly what `jmp@2` requires.
* it doesn't patch a bug in `jmp@2.0`
* it doesn't add any functionality to `jmp@2` (that I'd release as a minor version update)
* it doesn't drop support for any functionality (that I'd release as a major version update)

`jmp` is a library and uses semver (i.e. it lets the user decide whether they want to use a specific version or they  are happy with `npm`'s choice).

The purpose of semver is exactly that (otherwise every time a dependency made a new release would trigger a cascade of releases in the depedants).

`jmp` doesn't release any assets that should be built in a reproducible manner (and thus, it doesn't publish a  `package-lick.json`).

**Comment by aminya** [comment]
I am not a fan of using `semver` for dependency management as it makes everything unreproducible. Releasing a new version is also a way of informing downstream about the changes in the behavior of JMP (caused by its dependencies in this case).

**Comment by n-riesco** [comment]
Releasing a new version wouldn't just be informing downstream.
It'd be forcing them to use the updated dependencies, and preventing them from downgrading if needed.

**Comment by n-riesco** [comment]
@aminya [`package-lock.json`](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json) was introduced exactly for that reason: to inform users of the versions needed to reproduce a build. The versions in  `package.json` describe compatibility.

**Pull request closed without merging**
